comicbin/config/routes.rb
Comicbin::Application.routes.draw do

  #set root as index
  root "comics#index"
  
  get "/comics" => "comics#index"
  get "/comics/new" => "comics#new"
  get "/comics/add" => "comics#add"

  get "/comics/show/:comic_id" => 'comics#show'
  get "/comics/delete/:comic_id" => 'comics#delete'

end

comicbin/app/models/comic.rb
class Comic < ActiveRecord::Base
end

comicbin/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

comicbin/app/controllers/comics_controller.rb
class ComicsController < ApplicationController

	def index
		#renders index by default
		@comics = Comic.all
	end

	def show	
		comic_id = params["comic_id"]
		@comic = Comic.find_by :id => comic_id
		render 'show'
	end

	def delete
		comic_id = params["comic_id"]

    	c = Comic.find_by(:id => comic_id)
    	c.destroy
    	redirect_to "/comics"
    end

    def new
    	render 'new'
    end 

    def add
    	@comic = Comic.new
    	@comic.title = params["title"]
    	@comic.description = params["description"]
    	@comic.image = params["image"]
    	@comic.save
    	redirect_to "/comics"
    end

	def test
		render 'test'
	end

end

comicbin/app/helpers/application_helper.rb
module ApplicationHelper
end

comicbin/app/views/comics/_form.html.erb
<div class='col-lg-6'>
  <div class='well'>

  <!-- WRITE THE CORRECT FORM HEADER AND BLOCK USING ERB -->
  <form action="/comics/add">


    <div class="form-group">
      <!-- DISPLAY A TITLE LABEL -->
      <!-- DISPLAY A TEXT FIELD AND ATTACH THE CLASS OF 'form-control' TO THIS FIELD -->
        <label for="title">Comic Title:</label>
        <input type="text" name="title" class="form-control" id="title" placeholder="Enter comic title">
    </div>
    <div class="form-group">
      <!-- DISPLAY A DESCRIPTION LABEL -->
      <!-- DISPLAY A TEXT FIELD AND ATTACH THE CLASS OF 'form-control' TO THIS FIELD -->
        <label for="description">Description:</label>
        <input type="text" name="description" class="form-control" id="description" placeholder="Enter comic description">
    </div>
    <div class="form-group">
      <!-- DISPLAY AN IMAGE LABEL -->
      <!-- DISPLAY A TEXT FIELD ATTACH THE CLASS OF 'form-control' TO THIS FIELD -->
        <label for="image">Cover Image:</label>
        <input type="text" name="image" class="form-control" id="image" placeholder="Enter comic image url">
    </div>

    <div class="actions">
      <!-- DISPLAY A SUBMIT BUTTON WITH A CLASS OF 'btn btn-primary' -->
      <button type="submit" class="btn btn-default">Submit</button>
    </div>

  </form>



  </div>
</div>

comicbin/app/views/comics/edit.html.erb
<div class='container'>
  <h2>Edit comic</h2>
</div>

<div class='row'>
  <!-- RENDER THE FORM PARTIAL HERE. -->
</div>

<div class='container'>
  <%= link_to 'Show comic', @comic %>
  <%= link_to 'Back to all comics', comics_path %>
</div>

comicbin/app/views/comics/index.html.erb
<% @comics.in_groups_of(4, false).each_with_index do |group, index| %>
  <div class="row">
    <% group.each do |comic| %>
      <div class='col-lg-3 test'>
        <!-- SHOW THE IMAGE OF THE COMIC BOOK AND MAKE THE ENTIRE IMAGE A LINK.
             ATTACH THE CLASS OF 'image-responsive' TO THIS LINK -->
             <%= link_to image_tag(comic.image, size: "275x425"), "/comics/show/#{comic.id}", class: 'image-responsive' %> 
             
      </div>
    <% end %>
  </div>
<% end %>

comicbin/app/views/comics/new.html.erb
<div class='container'>
  <h2>Add a new comic</h2>
</div>

<div class='row'>
  <!-- RENDER THE FORM PARTIAL HERE. -->
  <!-- just used HTML form for now -->
 <%= render "form" %>

<div class='container'>
  <%= link_to 'Back to all comics', "/comics" %>
</div>


<!--
    <div class="col-md-6">
    <form action="/comics/add">
      <div class="form-group">
        <label for="title">Comic Title:</label>
        <input type="text" name="title" class="form-control" id="title" placeholder="Enter comic title">
      </div>
      <div class="form-group">
        <label for="description">Description:</label>
        <input type="text" name="description" class="form-control" id="description" placeholder="Enter comic description">
      </div>
      <div class="form-group">
        <label for="image">Cover Image:</label>
        <input type="text" name="image" class="form-control" id="image" placeholder="Enter comic image url">
      </div>
      <button type="submit" class="btn btn-default">Submit</button>
    </form>
	

	-->
	</div>

comicbin/app/views/comics/show.html.erb
<div class='row'>
  <div class='col-md-5'>
      <!-- INSERT COMIC COVER IMAGE HERE WITH ERB.
           ATTACH THE CLASS of 'img-responsive' TO THIS LINK -->
      <%= image_tag(@comic.image, size: "275x425", class: 'image-responsive') %>
  </div>
  <div class='col-md-7'>
    <h1><%=@comic.title%></h1>
    <h4><%=@comic.description.to_s%></h4>
    <%= link_to "Delete Comic", "/comics/delete/#{@comic.id}", class: 'btn btn-warning', :confirm => "Are you sure you want delete?" %>
    <!-- INSERT LINK TO DELETE A COMIC BOOK HERE.
         ATTACH A CLASS of 'btn btn-warning' TO THIS LINK.
         ALSO INCLUDE A CONFIRMATION MESSAGE 'Are you sure?' -->
  </div>
</div>

comicbin/app/views/comics/test.html.erb
hello world

comicbin/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Comic Bin</title>
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= stylesheet_link_tag    'http://fonts.googleapis.com/css?family=Oswald:400,700' %>
    <%= csrf_meta_tags %>
  </head>


  <body>
    <div class='container'>
      <div class='page-header'>
        <%= link_to 'Add a comic book', '/comics/new', class: 'btn btn-success pull-right add' %>
        <%= link_to 'View all comics', '/comics', class: 'btn btn-primary pull-right add' %>
        <h1 class='logo'>Comic Bin</h1>
      </div>
      <%= yield %>
    </div>
  </body>

</html>